= Microprofile Showcase Application

== General information

The application consists of several Microservices and a Web-Application managing a conference :

* `microservice-schedule` : Schedule of the conference
* `microservice-session` : Sessions of the conference
* `microservice-speaker` : Speakers of the conference
* `microservice-vote` : Votes for each session
* `web-application` : Frontend Angular2 | Bootstrap4 | EE7 web application

== Technologies

* Java
* Micro Profile
* JAX-RS 2.0 / JSON-P 1.0 / CDI 1.1

== Setup

* Build the projects using Maven (`mvn clean install`) or (`mvn -fn clean install`) to skip over failed tests.
* To get the technical documentation, just `mvn clean generate-resources` under the `docs` directory. You will get a PDF and HTML version of the documentation under `docs/target/generated-docs`

== Development

----
mvn clean install -DskipTests
----

=== Run Services

* `microservice-schedule`: TBC
* `microservice-session` : TBC
* `microservice-speaker` : TBC
* `microservice-vote` : TBC

=== Run UI

.Console 1
----
mvn clean package tomee:run -pl :web-application -DskipTests
----

.Console 2
----
$ cd web-application
$ mvn frontend:gulp
----

== Tests

mvn clean test

== Common problems/bugs


== Access to staging/beta/production

* https://github.com/microprofile/microprofile-conference

== Notes

This application is a collaborative demonstration application by:

* Liberty Profile
* London Java Community
* Red Hat
* Tomitribe
* Payara
