= Microprofile Showcase Application

== General information

The application consists of several Microservices and a Web-Application managing a conference :

* `microservice-schedule` : schedule of the conference
* `microservice-session` : sessions of the conference
* `microservice-speaker` : speakers of the conference
* `microservice-vote` : votes for each session

== Technologies

* Java
* Micro Profile
* JAX-RS 2.0 / JSON-P 1.0 / CDI 1.1

== Setup

* Build the projects using Maven (`mvn clean install`) or (`mvn -fn clean install`) to skip over failed tests.
* To get the technical documentation, just `mvn clean generate-resources` under the `docs` directory. You will get a PDF and HTML version of the documentation under `docs/target/generated-docs`

== Development


== Tests


== Common problems/bugs


== Access to staging/beta/production

* https://github.com/microprofile/microprofile-conference

== Notes

This application is a collaborative demonstration application by:

* Liberty Profile
* London Java Community
* Red Hat
* Tomitribe
* Payara
