= Microprofile Showcase Application

== microservice-schedule-kumuluzee
Provided using link:https://ee.kumuluz.com/[KumuluzEE 2.4.1]

*Build and run the service*
```
cd microservice-schedule-kumuluzee
mvn clean package
java [-D<OPTION>] -jar target/microservice-schedule-kumuluzee.jar
```

*Address & Port Bindings*

.Session Service Options
|===
|Flag |Description| Default

| kumuluzee.server.http.address=<address>
| HTTP bind interface
| 0.0.0.0

| kumuluzee.server.http.port=<port>
| HTTP port
| 8080
|===

For example, if you want to change the HTTP port to 6060, run the application like this:

----
java -Dkumuluzee.server.http.port=6060 -jar target/microservice-schedule-kumuluzee.jar
----

Click on this link to verify that everything ran fine: http://localhost:6060/schedule/all

=== Health Checks

Microservice includes two health checks:

- DiskHealthCheck: Checks, if there is more than 100MB disk space available
- SelfHealthCheck: Checks, if the `/schedule/all` endpoint is accessible

You can view the status of the health checks by visiting this link: http://localhost:6060/health

Health Checks are provided using link:https://github.com/kumuluz/kumuluzee-health[KumuluzEE Health],
the KumuluzEE implementation of the
link:https://github.com/eclipse/microprofile-health[MicroProfile Health Specification].

=== Configuration

Microservice uses link:https://github.com/kumuluz/kumuluzee-config-mp[KumuluzEE Config MicroProfile],
the KumuluzEE implementation of the
link:https://microprofile.io/project/eclipse/microprofile-config[MicroProfile Configuration Specification].

KumuluzEE Config Microprofile enables access to the configuration values from multiple configuration
sources like system properties, environment variables and configuration files, as well as configuration servers
like etcd and Consul.

This microservice uses configuration file `config.yml` to configure the HTTP method of
SelfHealthCheck.

```
@Inject
@ConfigProperty(name = "health.health-check-http-method", defaultValue = "GET")
String healthCheckHttpMethod;
```

=== Metrics

Microservice collects metrics from the JVM and requests, that pass through the `/schedule/*` endpoints.
Metrics are exposed in two formats:

- JSON: Available on this link: http://localhost:6060/metrics
- Prometheus: Available on this link: http://localhost:6060/prometheus

Metrics are provided using link:https://github.com/kumuluz/kumuluzee-metrics[KumuluzEE Metrics].
