= microservice-schedule
The Schedule service is provided using a special microprofile release of link:http://www.payara.fish/payara_micro[Payara Micro] which can be downloaded from link:http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22payara-microprofile%22[Maven Central]

*Build and run the service*
When building the service Payara Microprofile packages both the war file and the microprofile runtime into a single UberJar for convenience.
```
cd microservice-schedule
mvn clean package
java -jar target\microservice-schedule.jar --port 6060
```

*Port Bindings*
By default the microservice would bind to port 8080, if this is not available it will bind to the next available port e.g. 8081. Specifying the port using --port as a command line option overrides this.

To verify that the schedule microservice is running, use the following link: http://localhost:6060/schedule/all

To see a full set options run the jar with the --help command line option or see the link:https://payara.gitbooks.io/payara-server/content/documentation/payara-micro/payara-micro.html[Payara Micro Documentation] for a full list of options.

=== Running on Liberty

Alternatively you can run this service on liberty by doing:

```
cd microservice-schedule
mvn -Pliberty package
java -jar target/microservice-schedule-liberty.jar
```